language: java
jdk: oraclejdk15
os: linux

env:
  global:
  - secure: BxmJN35YMrLYaJCQj86Sq5emDIV5G1F1tn/Ec1XVrwWLNXzXt3a/eFAFwFsalNEC1f1vj2ut3xpXUUgDguwmXBXDAvlR5C6ZGMRk84DeO9HaCKoVdrmaqFNB+YfFLiTTU4V7UXsEWjEOZbSy7K06pLJ3AcRPtPgh2tmay66HKQUwHgTH/JK7vQ45lwt2hdOrpXYM7S6cmHOwFk8KBLHnDSpbtmkvLzAxhoXjf0iQlR3wCWyMHwroVAy7gK6DScqJzbCKGH1X2kEmwTHw2BDQKJoVDB1e+zsBij3PIHXDlgre41WUT6PYosfMftt4ivVSuGpWq/LW2dc6bIXpxt5r5OtnRb+8vusnzFVac0GkEjOZSJD7MUhGdRrHdHT4VGpMtlLIdviryeLMF1pKWU8Zc76VZYfrL0ik1JbWV4tb41kLZeNOj2bp3EPUeJ5J3g4iHchsGPKCXjn7C16qp8nJKKuFvm8yRyW1W4hEv6k6DcwJ8ajdnZavjSeIhIgW2vhX2svkKj3rVzKZ6lHbdbAgAht4qS71i8HpAzfzwbVyJP+e7yyhF8wsdW9T7AoROcxl2Iv2Ekowlc+t9oOH7uu7ir3IWPrKWvjTjqdwSpmktg2VHw4lTS6dMh/L6kT7/a1DhpYZKnWQst/n72D34rGH/MbdlV6bDCzKlK3uAMjcbmM=

script:
    - cd LifeBookProject/LifeBookProject
    - echo "Maven dependencies"
    - mvn install -DskipTests
    - echo "Unit tests"
    - mvn test

after_success:
    - mvn checkstyle:check
    - mvn javadoc:javadoc
    - cd ..
    - cd ..
    - ls
    - bash push-javadoc-to-gh-pages.sh
    - cd LifeBookProject/LifeBookProject

deploy:
    provider: heroku
    skip-cleanup: true
    api-key:
        secure: F/aMjLQSMUIEKlsmX1sF2t48lJMPN1DGUtec9worrbVcFymN6mxCGFy9YNemB55YiFXRX1dHNIzFeKyUmR+ra9GqZ1bXqMmfPCPcVw0vgNPTTrdK0B/iw2isJCGd2C0NwZuL9rgOKP2BoPCSR2mSmlkesDEuDThWPWS75NNzVlqom9EmXe981f1wjo36zrCYXfjE5z/ZmzHKUq0hnUp4woVqPyiAzs2yH8j8CWDq20As2xOUnxr+THbw15OUN9ujdN/7k1ovaLKir0H+nx193D+Vk/QNwBhIET70BajdNsirpclrYe7Z4zMlhIRahieoo1mrJY+I72yNDYlb2/nbfCc1bSJldt55QLkD8trDK+EwNHJ8+LzGsWZqzDiDeEICba0WQT0mIUUndReDbWTS/TgjXlo6jBq4DmPYOTZA87fPtvgbGEcZf9cLLC3eabonaxdgFDkEnLrEAlxeIYGKRolFpiGLNX/SxrgsrTbun++I8e2sxIebrdQIOaAspUhPHtYix97KpF9jquPkEJqxxhEeUdfl7OH/eG2wB+HVwhuB/8dOwaksqLsKQq1g23dR9M0H0oIiAv5SwyVHIVZ2vgFcBitnFQ1ych5lW9ta87vgrbNFW5ZKCsHpTjJHpjookSRSh/DNgUcSQCqhOZXnXAFVK6e7ZcRM1sdWH9+44WU=
    app: lifebook-project

branches:
    only:
    - master

cache:
  directories:
  - $HOME/.m2