language: java
jdk: oraclejdk15
os: linux

script:
    - echo "Maven dependencies"
    - mvn install -DskipTests
    - echo "Unit tests"
    - mvn test

branches:
    only:
    - database

cache:
  directories:
  - $HOME/.m2