language: java
jdk: oraclejdk15
os: linux

jobs:
    build:
        steps:
            -name: "Maven dependencies"
             run: mvn install -DskipTests
            -name: "Unit tests"
             run: mvn test

branches:
    only:
    - database

cache:
  directories:
  - $HOME/.m2