language: java
jdk: oraclejdk15
os: linux
env:
  global:
script:
- cd LifeBookProject/LifeBookProject
- echo "Maven dependencies"
- mvn install -DskipTests
- echo "Unit tests"
- mvn test
after_success:
- mvn checkstyle:check

cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: Cc7GnG++fSDwKUGue73GOy8qMxIMMcAzPHYbl6dAaaLoo+yc1yEbEGwXWn5VG9hCSoCZZxaIdymuCAPvJ8LpLg82d/nm1mK6HKV9qxBrX1XECBNK9re4tXwg6+82RMvM6OqCWO+D83hdK0Cji4LDQf9XJ59lPLRFZFnAjS4PmWts+odSD4DRHEfk/LJC3Cm6yExLh0y1qbH+ZILnakGU/1Q4/zv8wcd29Okk/3v3ReQrVDJH1HyNnWtvqANbrOePGISoBfbCjTkmQzMTW2lRbynM/k51Xay3Tn8xgbHamKf/gLY8yzW2bft3RV19KTtyoCGrzxCSFB3DL1tVzAt21RSc1rAJ9X3Xb1u0jWtOB5/moGEVQb7tLy6IwGRK8VPTbup8KUHZ02KDlIWNsDfCrev48vv2okaFCdRbZU9vNHthXpzpXWaeX5y0cdWUdVB4Nmg24rQoq5cY0FuLV+Kjb2hDeC6rFfxtjkR50Rnrji9+C0D6gmWtQjxUolI+vYTlPkCGLs7k1pCgtkuecp/DKMMQhGDC1N3NQ9SJwfbhlvVjW3QeBohuEUqQ2jpnvCUEgf9t75JjDaEBMsLZRsqjZKp/TMIGSbR9XgTnWGoT3W6ClgWQxiBccAIHKN05MieY8ueOqweVy5gFUtq8xT8/w6p3Ha1rGIn8J4TXEx44FYI=
  app: lifebookproject
  on:
    repo: ELTE-Projekt-Eszkozok-LifeBook/LifeBook-Project
