language: java
jdk: oraclejdk15
os: linux

script:
    - cd LifeBookProject/LifeBookProject
    - echo "Maven dependencies"
    - mvn install -DskipTests
    - echo "Unit tests"
    - mvn test

after_success:
    - mvn javadoc:javadoc
    - cd ..
    - cd ..
    - ls
    - bash push-javadoc-to-gh-pages.sh

branches:
    only:
    - database

cache:
  directories:
  - $HOME/.m2